import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ShootingStars } from "@/components/ui/shooting-starts";
import { StarsBackground } from "@/components/ui/stars-background";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}  antialiased`}>
        <ShootingStars />
        <StarsBackground />
        <div className="z-2 relative p-10">{children}</div>
      </body>
    </html>
  );
}
